import { Component } from '@angular/core';
import { Datum } from '@ng9/business-console'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'test';
  public columns: Array<string>;
  public data: Array<Datum>;

  constructor() {
    this.columns = [
      'status',
      'productName',
      'totalEarnings',
      'activeCustomers',
      'numOfBilling',
      'ropstenNetworkOn',
      'creationTimestamp',
      'columnClicked',
    ];
    this.data = [{
      productID: 'cBvn45paZ7s63nK89CerAKzRfTz5A5Po',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 5,
      tags: null,
      productName: 'The laughing man',
      productDescription: null,
      creationTimestamp: '1562227047',
      lastUpdateTimestamp: '1562227047',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/5722eeb527790c397846216f2ab605e1.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 15,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    },
    {
      productID: 'Ot6gksy3FRuwnDmJzFyxFWZbpl8OHlsh',
      businessID: 'y2beEPTM49El0wXfAwRlzSRYzKcnIBD0',
      categoryID: 1,
      tags: null,
      productName: 'fSingle Payments',
      productDescription: null,
      creationTimestamp: '1561560334',
      lastUpdateTimestamp: '1561560334',
      productUrl: 'www.example.com',
      imageUrl:
        'https://preassets.pumapay.io/product-img/acdda1217729a6ad377bf9eb912163f0.png',
      verified: false,
      usdTotalEarnings: '0',
      eurTotalEarnings: '0',
      jpyTotalEarnings: '0',
      gbpTotalEarnings: '0',
      activeCustomers: 0,
      numOfBilling: 6,
      enabled: true,
      totalEarnings: 0,
      status: 'active',
    }]

  }
}
